### ISSUE TITLE
Crash when shift-clicking on the Floower Pots inventory slot while it is empty

### ISSUE THREAD

**Issue by angelnc1989** [fredtargaryen/Floocraft#9]
Minecraft 1.11.2
Forge 13.20.0.2304
Floocraft 1.7.7 (patch 1)

[Crash report](https://pastebin.com/RrLZLh9h)

I placed a Floower Pot between two fireplaces in my test world. When I shift-clicked the inventory slot of the Floower Pot the game crashed. The crash is reproducable.

**Comment by fredtargaryen** [comment]
Fixed. I will upload patch 2 at some point today... unless I forget. Thank you!
Update: done.

**Comment by angelnc1989** [comment]
I just noticed that this is still not fixed. (This time playing on 1.12)

**Comment by fredtargaryen** [comment]
Sorry to hear that. I took a look at the latest version for 1.12 and haven't been able to reproduce it. What exactly did you do? Edit: another crash report would also be helpful if it's not the same.

**Comment by angelnc1989** [comment]
I can't find the crash-report and can't reproduce it either anymore. I definitly crashed once. If it happens again I will make sure to upload the crash-report.

**Comment by fredtargaryen** [comment]
OK, cheers.
